const fakedb = {
  works: [
    {
      name: "Hotel Marina",
      committee: "Nebula 7",
      date: "Dec 2020",
      description: "Website for Hotel Marina Charming Rooms.",
      url: "https://hotelmarinafinale.it",
    },
    {
      name: "No Season",
      committee: "Nebula 7",
      date: "Nov 2020",
      description: "Website for Studio Pesca No Season.",
      url: "https://noseason.studiopesca.com",
    },
    {
      name: "Fondo Ristorante",
      committee: "Nebula 7",
      date: "Sep 2020",
      description: "Webiste for Fondo Restaurant.",
      url: "https://fondoristorante.it",
    },
    {
      name: "Madamé Lounge Bar",
      committee: "Madame Lounge Bar",
      date: "Jun 2020",
      description: "Website for online digital menu.",
      url: "https://madameloungebar.herokuapp.com",
    },
    {
      name: "Centro Ippico Punta Ala",
      committee: "Nebula 7",
      date: "May 2020",
      description: "Landing page for Centro Ippico Punta Ala.",
      url: "https://centroippicopuntaala.it",
    },
    {
      name: "Jill Emanuelle",
      committee: "Nebula 7",
      date: "Feb 2020",
      description: "Photography portfolio for Jill Emanuelle.",
      url: "https://jillemanuelle.com",
    },
    {
      name: "Bottega Veneta Website",
      committee: "Nebula 7",
      date: "Oct 2021",
      description: "I worked on the working prototype for the new Bottega Veneta website.",
      url: "",
    },
    {
      name: "Bottega Veneta Brand Book",
      committee: "Nebula 7",
      date: "Oct 2021",
      description: "I worked on the working prototype for the Bottega Veneta brand book.",
      url: "",
    },
    {
      name: "Sylva. Instalacion artistica",
      committee: "Nebula 7",
      date: "Oct 2021",
      description: "I partecipated in the realization of the graphic interface projected at the princess of asturias award in 2021.\nIn collaboration of @nebula7, @maid.office & @abbgroup.",
      url: "",
    },
  ],
  skills: ["web development", "problem solving", "PHP", "MySQL", "Javascript", "HTML5", "CSS3", "NodeJS",
    "MongoDB", "VueJS", "NuxtJS", "Angular", "Python",
    "Express", "Mongoose", "Git", "GitHub", "Bitbucket", "GitLab", "Java"],
  about: {
    body: "My name is Dario Tecchia, I was born on September 16, 1994 and currently live in Sorrento, Italy. Since childhood I have developed a great passion for the computer world. I am particularly attracted by web technologies and frontend development. I currently work occasionally with [Nebula7] with whom I have developed some websites.",
    education: "I enrolled myself at Computer Science course at University of Salerno in 2013. During these years, I improved skills in Programming and Problem Solving. I obtained the Bachelor's Degree defending a thesis on TiVeJS: A Javascript application for the recognition of diagrammatic languages proposed by Prof. Gennaro Costagliola and PhD M. De Rosa. After, I chosed to begin a master degree in Computer Science, with address Software Engineering and IT Management. Currently, I study to obtain the Master's Degree.",
    name: "Dario Tecchia",
  }
}